/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.test.db.enums;


import com.razz.eva.test.db.DefaultSchema;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:004"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum BubalehsState implements EnumType {

    SERVED("SERVED"),

    CONSUMED("CONSUMED");

    private final String literal;

    private BubalehsState(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "bubalehs_state";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static BubalehsState lookupLiteral(String literal) {
        return EnumType.lookupLiteral(BubalehsState.class, literal);
    }
}
