/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.events.db;


import com.razz.eva.events.db.tables.ModelEvents;
import com.razz.eva.events.db.tables.UowEvents;
import com.razz.eva.events.db.tables.UowEventsTemplate;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4",
        "schema version:001"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Events extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>events</code>
     */
    public static final Events EVENTS = new Events();

    /**
     * The table <code>events.model_events</code>.
     */
    public final ModelEvents MODEL_EVENTS = ModelEvents.MODEL_EVENTS;

    /**
     * The table <code>events.uow_events</code>.
     */
    public final UowEvents UOW_EVENTS = UowEvents.UOW_EVENTS;

    /**
     * The table <code>events.uow_events_template</code>.
     */
    public final UowEventsTemplate UOW_EVENTS_TEMPLATE = UowEventsTemplate.UOW_EVENTS_TEMPLATE;

    /**
     * No further instances allowed
     */
    private Events() {
        super("events", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ModelEvents.MODEL_EVENTS,
            UowEvents.UOW_EVENTS,
            UowEventsTemplate.UOW_EVENTS_TEMPLATE
        );
    }
}
