/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.events.db;


import com.razz.eva.events.db.tables.ModelEvents;
import com.razz.eva.events.db.tables.UowEvents;
import com.razz.eva.events.db.tables.UowEventsTemplate;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables in events.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4",
        "schema version:001"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MODEL_EVENTS_INSERTED_AT_IDX = Internal.createIndex(DSL.name("model_events_inserted_at_idx"), ModelEvents.MODEL_EVENTS, new OrderField[] { ModelEvents.MODEL_EVENTS.INSERTED_AT }, false);
    public static final Index UOW_EVENTS_INSERTED_AT_IDX = Internal.createIndex(DSL.name("uow_events_inserted_at_idx"), UowEvents.UOW_EVENTS, new OrderField[] { UowEvents.UOW_EVENTS.INSERTED_AT }, false);
    public static final Index UOW_EVENTS_TEMPLATE_NAME_IDEMPOTENCY_KEY_IDX = Internal.createIndex(DSL.name("uow_events_template_name_idempotency_key_idx"), UowEventsTemplate.UOW_EVENTS_TEMPLATE, new OrderField[] { UowEventsTemplate.UOW_EVENTS_TEMPLATE.NAME, UowEventsTemplate.UOW_EVENTS_TEMPLATE.IDEMPOTENCY_KEY }, true);
}
