/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.events.db;


import com.razz.eva.events.db.tables.ModelEvents;
import com.razz.eva.events.db.tables.UowEvents;
import com.razz.eva.events.db.tables.UowEventsTemplate;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in events.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4",
        "schema version:001"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * PARTITIONED
     */
    public static final ModelEvents MODEL_EVENTS = ModelEvents.MODEL_EVENTS;

    /**
     * PARTITIONED
     */
    public static final UowEvents UOW_EVENTS = UowEvents.UOW_EVENTS;

    /**
     * The table <code>events.uow_events_template</code>.
     */
    public static final UowEventsTemplate UOW_EVENTS_TEMPLATE = UowEventsTemplate.UOW_EVENTS_TEMPLATE;
}
