/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.test.db.tables.records;


import com.razz.eva.test.db.enums.BubalehsState;
import com.razz.eva.test.db.tables.Bubalehs;

import java.time.Instant;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:004"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BubalehsRecord extends UpdatableRecordImpl<BubalehsRecord> implements com.razz.jooq.record.TypedStatefulEntityRecord<UUID, BubalehsState>, Record9<UUID, UUID, BubalehsState, String, Instant, String, Instant, Instant, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bubalehs.id</code>.
     */
    public BubalehsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>bubalehs.employee_id</code>.
     */
    public BubalehsRecord setEmployeeId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.employee_id</code>.
     */
    public UUID getEmployeeId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>bubalehs.state</code>.
     */
    public BubalehsRecord setState(BubalehsState value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.state</code>.
     */
    public BubalehsState getState() {
        return (BubalehsState) get(2);
    }

    /**
     * Setter for <code>bubalehs.taste</code>.
     */
    public BubalehsRecord setTaste(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.taste</code>.
     */
    public String getTaste() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bubalehs.produced_on</code>.
     */
    public BubalehsRecord setProducedOn(Instant value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.produced_on</code>.
     */
    public Instant getProducedOn() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>bubalehs.volume</code>.
     */
    public BubalehsRecord setVolume(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.volume</code>.
     */
    public String getVolume() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bubalehs.record_updated_at</code>.
     */
    public BubalehsRecord setRecordUpdatedAt(Instant value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.record_updated_at</code>.
     */
    public Instant getRecordUpdatedAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>bubalehs.record_created_at</code>.
     */
    public BubalehsRecord setRecordCreatedAt(Instant value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.record_created_at</code>.
     */
    public Instant getRecordCreatedAt() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>bubalehs.version</code>.
     */
    public BubalehsRecord setVersion(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>bubalehs.version</code>.
     */
    public Long getVersion() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, UUID, BubalehsState, String, Instant, String, Instant, Instant, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, UUID, BubalehsState, String, Instant, String, Instant, Instant, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Bubalehs.BUBALEHS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Bubalehs.BUBALEHS.EMPLOYEE_ID;
    }

    @Override
    public Field<BubalehsState> field3() {
        return Bubalehs.BUBALEHS.STATE;
    }

    @Override
    public Field<String> field4() {
        return Bubalehs.BUBALEHS.TASTE;
    }

    @Override
    public Field<Instant> field5() {
        return Bubalehs.BUBALEHS.PRODUCED_ON;
    }

    @Override
    public Field<String> field6() {
        return Bubalehs.BUBALEHS.VOLUME;
    }

    @Override
    public Field<Instant> field7() {
        return Bubalehs.BUBALEHS.RECORD_UPDATED_AT;
    }

    @Override
    public Field<Instant> field8() {
        return Bubalehs.BUBALEHS.RECORD_CREATED_AT;
    }

    @Override
    public Field<Long> field9() {
        return Bubalehs.BUBALEHS.VERSION;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getEmployeeId();
    }

    @Override
    public BubalehsState component3() {
        return getState();
    }

    @Override
    public String component4() {
        return getTaste();
    }

    @Override
    public Instant component5() {
        return getProducedOn();
    }

    @Override
    public String component6() {
        return getVolume();
    }

    @Override
    public Instant component7() {
        return getRecordUpdatedAt();
    }

    @Override
    public Instant component8() {
        return getRecordCreatedAt();
    }

    @Override
    public Long component9() {
        return getVersion();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getEmployeeId();
    }

    @Override
    public BubalehsState value3() {
        return getState();
    }

    @Override
    public String value4() {
        return getTaste();
    }

    @Override
    public Instant value5() {
        return getProducedOn();
    }

    @Override
    public String value6() {
        return getVolume();
    }

    @Override
    public Instant value7() {
        return getRecordUpdatedAt();
    }

    @Override
    public Instant value8() {
        return getRecordCreatedAt();
    }

    @Override
    public Long value9() {
        return getVersion();
    }

    @Override
    public BubalehsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public BubalehsRecord value2(UUID value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public BubalehsRecord value3(BubalehsState value) {
        setState(value);
        return this;
    }

    @Override
    public BubalehsRecord value4(String value) {
        setTaste(value);
        return this;
    }

    @Override
    public BubalehsRecord value5(Instant value) {
        setProducedOn(value);
        return this;
    }

    @Override
    public BubalehsRecord value6(String value) {
        setVolume(value);
        return this;
    }

    @Override
    public BubalehsRecord value7(Instant value) {
        setRecordUpdatedAt(value);
        return this;
    }

    @Override
    public BubalehsRecord value8(Instant value) {
        setRecordCreatedAt(value);
        return this;
    }

    @Override
    public BubalehsRecord value9(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public BubalehsRecord values(UUID value1, UUID value2, BubalehsState value3, String value4, Instant value5, String value6, Instant value7, Instant value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BubalehsRecord
     */
    public BubalehsRecord() {
        super(Bubalehs.BUBALEHS);
    }

    /**
     * Create a detached, initialised BubalehsRecord
     */
    public BubalehsRecord(UUID id, UUID employeeId, BubalehsState state, String taste, Instant producedOn, String volume, Instant recordUpdatedAt, Instant recordCreatedAt, Long version) {
        super(Bubalehs.BUBALEHS);

        setId(id);
        setEmployeeId(employeeId);
        setState(state);
        setTaste(taste);
        setProducedOn(producedOn);
        setVolume(volume);
        setRecordUpdatedAt(recordUpdatedAt);
        setRecordCreatedAt(recordCreatedAt);
        setVersion(version);
    }
}
