/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.test.schema.enums;


import com.razz.eva.test.schema.DefaultSchema;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:004"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum DepartmentsState implements EnumType {

    OWNED("OWNED"),

    ORPHANED("ORPHANED");

    private final String literal;

    private DepartmentsState(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "departments_state";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static DepartmentsState lookupLiteral(String literal) {
        return EnumType.lookupLiteral(DepartmentsState.class, literal);
    }
}
