package com.razz.eva.test.schema.tables;

import java.sql.Date;
import java.util.Collection;
import java.util.UUID;

import javax.annotation.processing.Generated;

import com.razz.eva.test.schema.DefaultSchema;
import com.razz.eva.test.schema.Keys;
import com.razz.eva.test.schema.tables.records.RationAllocationRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
        "schema version:014"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RationAllocation extends TableImpl<RationAllocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ration_allocation</code>
     */
    public static final RationAllocation RATION_ALLOCATION = new RationAllocation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RationAllocationRecord> getRecordType() {
        return RationAllocationRecord.class;
    }

    /**
     * The column <code>ration_allocation.employee_id</code>.
     */
    public final TableField<RationAllocationRecord, UUID> EMPLOYEE_ID = createField(DSL.name("employee_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ration_allocation.ration</code>.
     */
    public final TableField<RationAllocationRecord, String> RATION = createField(DSL.name("ration"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ration_allocation.effective_date</code>.
     */
    public final TableField<RationAllocationRecord, Date> EFFECTIVE_DATE = createField(DSL.name("effective_date"), SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>ration_allocation.quantity</code>.
     */
    public final TableField<RationAllocationRecord, Integer> QUANTITY = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "");

    private RationAllocation(Name alias, Table<RationAllocationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RationAllocation(Name alias, Table<RationAllocationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ration_allocation</code> table reference
     */
    public RationAllocation(String alias) {
        this(DSL.name(alias), RATION_ALLOCATION);
    }

    /**
     * Create an aliased <code>ration_allocation</code> table reference
     */
    public RationAllocation(Name alias) {
        this(alias, RATION_ALLOCATION);
    }

    /**
     * Create a <code>ration_allocation</code> table reference
     */
    public RationAllocation() {
        this(DSL.name("ration_allocation"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<RationAllocationRecord> getPrimaryKey() {
        return Keys.RATION_ALLOCATION_PKEY;
    }

    @Override
    public RationAllocation as(String alias) {
        return new RationAllocation(DSL.name(alias), this);
    }

    @Override
    public RationAllocation as(Name alias) {
        return new RationAllocation(alias, this);
    }

    @Override
    public RationAllocation as(Table<?> alias) {
        return new RationAllocation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RationAllocation rename(String name) {
        return new RationAllocation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RationAllocation rename(Name name) {
        return new RationAllocation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RationAllocation rename(Table<?> name) {
        return new RationAllocation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RationAllocation where(Condition condition) {
        return new RationAllocation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RationAllocation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RationAllocation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RationAllocation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RationAllocation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RationAllocation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RationAllocation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RationAllocation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RationAllocation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RationAllocation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
