package com.razz.eva.test.schema.tables;

import java.util.Collection;
import java.util.UUID;

import javax.annotation.processing.Generated;

import com.razz.eva.test.schema.DefaultSchema;
import com.razz.eva.test.schema.Keys;
import com.razz.eva.test.schema.tables.records.TxnViewRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
        "schema version:014"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TxnView extends TableImpl<TxnViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>txn_view</code>
     */
    public static final TxnView TXN_VIEW = new TxnView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TxnViewRecord> getRecordType() {
        return TxnViewRecord.class;
    }

    /**
     * The column <code>txn_view.transaction_id</code>.
     */
    public final TableField<TxnViewRecord, UUID> TRANSACTION_ID = createField(DSL.name("transaction_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>txn_view.value</code>.
     */
    public final TableField<TxnViewRecord, Integer> VALUE = createField(DSL.name("value"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>txn_view.currency</code>.
     */
    public final TableField<TxnViewRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.CLOB.nullable(false), this, "");

    private TxnView(Name alias, Table<TxnViewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TxnView(Name alias, Table<TxnViewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>txn_view</code> table reference
     */
    public TxnView(String alias) {
        this(DSL.name(alias), TXN_VIEW);
    }

    /**
     * Create an aliased <code>txn_view</code> table reference
     */
    public TxnView(Name alias) {
        this(alias, TXN_VIEW);
    }

    /**
     * Create a <code>txn_view</code> table reference
     */
    public TxnView() {
        this(DSL.name("txn_view"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<TxnViewRecord> getPrimaryKey() {
        return Keys.TXN_VIEW_PKEY;
    }

    @Override
    public TxnView as(String alias) {
        return new TxnView(DSL.name(alias), this);
    }

    @Override
    public TxnView as(Name alias) {
        return new TxnView(alias, this);
    }

    @Override
    public TxnView as(Table<?> alias) {
        return new TxnView(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TxnView rename(String name) {
        return new TxnView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TxnView rename(Name name) {
        return new TxnView(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TxnView rename(Table<?> name) {
        return new TxnView(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TxnView where(Condition condition) {
        return new TxnView(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TxnView where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TxnView where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TxnView where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TxnView where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TxnView where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TxnView where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TxnView where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TxnView whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TxnView whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
