/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.examples.schema.db;


import com.razz.eva.examples.schema.db.tables.User;
import com.razz.eva.examples.schema.db.tables.Wallet;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:001"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>wallet</code>.
     */
    public static final Wallet WALLET = Wallet.WALLET;
}
