/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.events.db.tables;


import com.razz.eva.events.db.Events;
import com.razz.eva.events.db.Indexes;
import com.razz.eva.events.db.tables.records.ModelEventsRecord;
import com.razz.jooq.converter.InstantConverter;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;


/**
 * PARTITIONED
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4",
        "schema version:001"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelEvents extends TableImpl<ModelEventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>events.model_events</code>
     */
    public static final ModelEvents MODEL_EVENTS = new ModelEvents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ModelEventsRecord> getRecordType() {
        return ModelEventsRecord.class;
    }

    /**
     * The column <code>events.model_events.id</code>.
     */
    public final TableField<ModelEventsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>events.model_events.uow_id</code>.
     */
    public final TableField<ModelEventsRecord, UUID> UOW_ID = createField(DSL.name("uow_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>events.model_events.model_id</code>.
     */
    public final TableField<ModelEventsRecord, String> MODEL_ID = createField(DSL.name("model_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>events.model_events.name</code>.
     */
    public final TableField<ModelEventsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>events.model_events.model_name</code>.
     */
    public final TableField<ModelEventsRecord, String> MODEL_NAME = createField(DSL.name("model_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>events.model_events.occurred_at</code>.
     */
    public final TableField<ModelEventsRecord, Instant> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.TIMESTAMP(6).nullable(false), this, "", new InstantConverter());

    /**
     * The column <code>events.model_events.inserted_at</code>.
     */
    public final TableField<ModelEventsRecord, Instant> INSERTED_AT = createField(DSL.name("inserted_at"), SQLDataType.TIMESTAMP(6).nullable(false).defaultValue(DSL.field("LOCALTIMESTAMP", SQLDataType.TIMESTAMP)), this, "", new InstantConverter());

    /**
     * The column <code>events.model_events.payload</code>.
     */
    public final TableField<ModelEventsRecord, String> PAYLOAD = createField(DSL.name("payload"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>events.model_events.tracing_context</code>.
     */
    public final TableField<ModelEventsRecord, String> TRACING_CONTEXT = createField(DSL.name("tracing_context"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field("'{}'::text", SQLDataType.CLOB)), this, "");

    /**
     * The column <code>events.model_events.incremental_query_id</code>.
     */
    public final TableField<ModelEventsRecord, Long> INCREMENTAL_QUERY_ID = createField(DSL.name("incremental_query_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    private ModelEvents(Name alias, Table<ModelEventsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ModelEvents(Name alias, Table<ModelEventsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("PARTITIONED"), TableOptions.table());
    }

    /**
     * Create an aliased <code>events.model_events</code> table reference
     */
    public ModelEvents(String alias) {
        this(DSL.name(alias), MODEL_EVENTS);
    }

    /**
     * Create an aliased <code>events.model_events</code> table reference
     */
    public ModelEvents(Name alias) {
        this(alias, MODEL_EVENTS);
    }

    /**
     * Create a <code>events.model_events</code> table reference
     */
    public ModelEvents() {
        this(DSL.name("model_events"), null);
    }

    public <O extends Record> ModelEvents(Table<O> child, ForeignKey<O, ModelEventsRecord> key) {
        super(child, key, MODEL_EVENTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Events.EVENTS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MODEL_EVENTS_INSERTED_AT_IDX);
    }

    @Override
    public Identity<ModelEventsRecord, Long> getIdentity() {
        return (Identity<ModelEventsRecord, Long>) super.getIdentity();
    }

    @Override
    public ModelEvents as(String alias) {
        return new ModelEvents(DSL.name(alias), this);
    }

    @Override
    public ModelEvents as(Name alias) {
        return new ModelEvents(alias, this);
    }

    @Override
    public ModelEvents as(Table<?> alias) {
        return new ModelEvents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ModelEvents rename(String name) {
        return new ModelEvents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ModelEvents rename(Name name) {
        return new ModelEvents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ModelEvents rename(Table<?> name) {
        return new ModelEvents(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, UUID, String, String, String, Instant, Instant, String, String, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super Instant, ? super Instant, ? super String, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super Instant, ? super Instant, ? super String, ? super String, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
