object versions {
    val java = org.gradle.api.JavaVersion.VERSION_21
    val jvm = "21"
    val kotlin = "2.2.21"
    val kotlin_coroutines = "1.10.2"
    val kotlin_serialization_json = "1.9.0"
    val kotest = "6.0.7"
    val jooq = "3.20.10"
    val flywaydb = "11.20.0"
    val opentelemetry = "1.57.0"
    val micrometer = "1.14.1"
    val detekt = "1.23.8"
    val logback = "1.5.24"
    val kotlin_logging = "3.0.5"
    val kotlin_slf4 = "1.10.2"
    val jackson = "2.19.1"
    val mockk = "1.14.7"
    val testcontainers = "2.0.3"
    val testcontainers_postgres = "1.21.4"
    val postgresql = "42.7.8"
    val vertx = "5.0.6"
    val hikari = "7.0.2"
    val kafka_clients = "3.8.0"
}

object libs {
    val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib:${versions.kotlin}"
    val kotlin_reflect = "org.jetbrains.kotlin:kotlin-reflect:${versions.kotlin}"
    val kotlin_serialization = "org.jetbrains.kotlin:kotlin-serialization:${versions.kotlin}"
    val kotlin_logging = "io.github.microutils:kotlin-logging:${versions.kotlin_logging}"
    val kotlin_slf4 = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:${versions.kotlin_slf4}"
    val kotlin_coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${versions.kotlin_coroutines}"
    val kotlinx_serialization = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:${versions.kotlin_serialization_json}"
    val kotlinx_serialization_json = "org.jetbrains.kotlinx:kotlinx-serialization-json:${versions.kotlin_serialization_json}"
    val kotest_runner = "io.kotest:kotest-runner-junit5-jvm:${versions.kotest}"
    val kotest_assertions_json = "io.kotest:kotest-assertions-json-jvm:${versions.kotest}"
    val kotest_assertions_core = "io.kotest:kotest-assertions-core-jvm:${versions.kotest}"
    val hikari = "com.zaxxer:HikariCP:${versions.hikari}"
    val jooq = "org.jooq:jooq:${versions.jooq}"
    val jooq_postgres = "org.jooq:jooq-postgres-extensions:${versions.jooq}"
    val logback = "ch.qos.logback:logback-classic:${versions.logback}"
    val opentelemetry_sdk = "io.opentelemetry:opentelemetry-sdk:${versions.opentelemetry}"
    val opentelemetry_sdk_testing = "io.opentelemetry:opentelemetry-sdk-testing:${versions.opentelemetry}"
    val opentelemetry_kotlin = "io.opentelemetry:opentelemetry-extension-kotlin:${versions.opentelemetry}"
    val flyway = "org.flywaydb:flyway-core:${versions.flywaydb}"
    val flyway_postgres = "org.flywaydb:flyway-database-postgresql:${versions.flywaydb}"
    val postgres = "org.postgresql:postgresql:${versions.postgresql}"
    val vertx_pg = "io.vertx:vertx-pg-client:${versions.vertx}"
    val vertx_kotlin = "io.vertx:vertx-lang-kotlin:${versions.vertx}"
    val vertx_kotlin_coroutines = "io.vertx:vertx-lang-kotlin-coroutines:${versions.vertx}"
    val mockk = "io.mockk:mockk:${versions.mockk}"
    val kafka_clients = "org.apache.kafka:kafka-clients:${versions.kafka_clients}"
    val testcontainers = "org.testcontainers:testcontainers:${versions.testcontainers}"
    val testcontainers_postgres = "org.testcontainers:postgresql:${versions.testcontainers_postgres}"
    val detekt = "io.gitlab.arturbosch.detekt:detekt-formatting:${versions.detekt}"
    val micrometer_prometheus = "io.micrometer:micrometer-registry-prometheus:${versions.micrometer}"

    val detekt_plugin = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:${versions.detekt}"
    val kotlin_plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${versions.kotlin}"
}
