/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.test.schema.tables.records;


import com.razz.eva.test.schema.tables.Employees;
import com.razz.jooq.record.BaseEntityRecord;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.time.Instant;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:004"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> implements BaseEntityRecord<UUID>, Record9<UUID, String, String, UUID, String, String, Instant, Instant, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>employees.id</code>.
     */
    public EmployeesRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>employees.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>employees.first_name</code>.
     */
    public EmployeesRecord setFirstName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>employees.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>employees.last_name</code>.
     */
    public EmployeesRecord setLastName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>employees.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>employees.department_id</code>.
     */
    public EmployeesRecord setDepartmentId(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>employees.department_id</code>.
     */
    public UUID getDepartmentId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>employees.email</code>.
     */
    public EmployeesRecord setEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>employees.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>employees.ration</code>.
     */
    public EmployeesRecord setRation(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>employees.ration</code>.
     */
    public String getRation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>employees.record_updated_at</code>.
     */
    public EmployeesRecord setRecordUpdatedAt(Instant value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>employees.record_updated_at</code>.
     */
    public Instant getRecordUpdatedAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>employees.record_created_at</code>.
     */
    public EmployeesRecord setRecordCreatedAt(Instant value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>employees.record_created_at</code>.
     */
    public Instant getRecordCreatedAt() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>employees.version</code>.
     */
    public EmployeesRecord setVersion(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>employees.version</code>.
     */
    public Long getVersion() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, String, String, UUID, String, String, Instant, Instant, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, String, String, UUID, String, String, Instant, Instant, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Employees.EMPLOYEES.ID;
    }

    @Override
    public Field<String> field2() {
        return Employees.EMPLOYEES.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Employees.EMPLOYEES.LAST_NAME;
    }

    @Override
    public Field<UUID> field4() {
        return Employees.EMPLOYEES.DEPARTMENT_ID;
    }

    @Override
    public Field<String> field5() {
        return Employees.EMPLOYEES.EMAIL;
    }

    @Override
    public Field<String> field6() {
        return Employees.EMPLOYEES.RATION;
    }

    @Override
    public Field<Instant> field7() {
        return Employees.EMPLOYEES.RECORD_UPDATED_AT;
    }

    @Override
    public Field<Instant> field8() {
        return Employees.EMPLOYEES.RECORD_CREATED_AT;
    }

    @Override
    public Field<Long> field9() {
        return Employees.EMPLOYEES.VERSION;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public UUID component4() {
        return getDepartmentId();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public String component6() {
        return getRation();
    }

    @Override
    public Instant component7() {
        return getRecordUpdatedAt();
    }

    @Override
    public Instant component8() {
        return getRecordCreatedAt();
    }

    @Override
    public Long component9() {
        return getVersion();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public UUID value4() {
        return getDepartmentId();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public String value6() {
        return getRation();
    }

    @Override
    public Instant value7() {
        return getRecordUpdatedAt();
    }

    @Override
    public Instant value8() {
        return getRecordCreatedAt();
    }

    @Override
    public Long value9() {
        return getVersion();
    }

    @Override
    public EmployeesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public EmployeesRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public EmployeesRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public EmployeesRecord value4(UUID value) {
        setDepartmentId(value);
        return this;
    }

    @Override
    public EmployeesRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public EmployeesRecord value6(String value) {
        setRation(value);
        return this;
    }

    @Override
    public EmployeesRecord value7(Instant value) {
        setRecordUpdatedAt(value);
        return this;
    }

    @Override
    public EmployeesRecord value8(Instant value) {
        setRecordCreatedAt(value);
        return this;
    }

    @Override
    public EmployeesRecord value9(Long value) {
        setVersion(value);
        return this;
    }

    @Override
    public EmployeesRecord values(UUID value1, String value2, String value3, UUID value4, String value5, String value6, Instant value7, Instant value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(UUID id, String firstName, String lastName, UUID departmentId, String email, String ration, Instant recordUpdatedAt, Instant recordCreatedAt, Long version) {
        super(Employees.EMPLOYEES);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setDepartmentId(departmentId);
        setEmail(email);
        setRation(ration);
        setRecordUpdatedAt(recordUpdatedAt);
        setRecordCreatedAt(recordCreatedAt);
        setVersion(version);
    }
}
