package com.razz.eva.test.schema.tables.records;

import java.sql.Date;
import java.util.UUID;

import javax.annotation.processing.Generated;

import com.razz.eva.test.schema.tables.RationAllocation;
import com.razz.jooq.record.BaseEntityRecord;
import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
        "schema version:014"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RationAllocationRecord extends UpdatableRecordImpl<RationAllocationRecord> implements BaseEntityRecord {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ration_allocation.employee_id</code>.
     */
    public RationAllocationRecord setEmployeeId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ration_allocation.employee_id</code>.
     */
    public UUID getEmployeeId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>ration_allocation.ration</code>.
     */
    public RationAllocationRecord setRation(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ration_allocation.ration</code>.
     */
    public String getRation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ration_allocation.effective_date</code>.
     */
    public RationAllocationRecord setEffectiveDate(Date value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ration_allocation.effective_date</code>.
     */
    public Date getEffectiveDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>ration_allocation.quantity</code>.
     */
    public RationAllocationRecord setQuantity(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ration_allocation.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<UUID, String, Date> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RationAllocationRecord
     */
    public RationAllocationRecord() {
        super(RationAllocation.RATION_ALLOCATION);
    }

    /**
     * Create a detached, initialised RationAllocationRecord
     */
    public RationAllocationRecord(UUID employeeId, String ration, Date effectiveDate, Integer quantity) {
        super(RationAllocation.RATION_ALLOCATION);

        setEmployeeId(employeeId);
        setRation(ration);
        setEffectiveDate(effectiveDate);
        setQuantity(quantity);
        resetTouchedOnNotNull();
    }
}
