package com.razz.eva.test.schema.tables.records;

import java.util.UUID;

import javax.annotation.processing.Generated;

import com.razz.eva.test.schema.tables.Tag;
import com.razz.jooq.record.BaseEntityRecord;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
        "schema version:014"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> implements BaseEntityRecord {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tag.subject_id</code>.
     */
    public TagRecord setSubjectId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>tag.subject_id</code>.
     */
    public UUID getSubjectId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>tag.name</code>.
     */
    public TagRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>tag.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tag.value</code>.
     */
    public TagRecord setValue(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>tag.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(UUID subjectId, String name, String value) {
        super(Tag.TAG);

        setSubjectId(subjectId);
        setName(name);
        setValue(value);
        resetTouchedOnNotNull();
    }
}
