package com.razz.eva.test.schema.tables.records;

import java.util.UUID;

import javax.annotation.processing.Generated;

import com.razz.eva.test.schema.tables.TxnView;
import com.razz.jooq.record.BaseEntityRecord;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10",
        "schema version:014"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TxnViewRecord extends UpdatableRecordImpl<TxnViewRecord> implements BaseEntityRecord {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>txn_view.transaction_id</code>.
     */
    public TxnViewRecord setTransactionId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>txn_view.transaction_id</code>.
     */
    public UUID getTransactionId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>txn_view.value</code>.
     */
    public TxnViewRecord setValue(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>txn_view.value</code>.
     */
    public Integer getValue() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>txn_view.currency</code>.
     */
    public TxnViewRecord setCurrency(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>txn_view.currency</code>.
     */
    public String getCurrency() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TxnViewRecord
     */
    public TxnViewRecord() {
        super(TxnView.TXN_VIEW);
    }

    /**
     * Create a detached, initialised TxnViewRecord
     */
    public TxnViewRecord(UUID transactionId, Integer value, String currency) {
        super(TxnView.TXN_VIEW);

        setTransactionId(transactionId);
        setValue(value);
        setCurrency(currency);
        resetTouchedOnNotNull();
    }
}
