/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.test.schema;


import com.razz.eva.test.schema.tables.Bubalehs;
import com.razz.eva.test.schema.tables.Departments;
import com.razz.eva.test.schema.tables.Employees;
import com.razz.eva.test.schema.tables.Shakshoukas;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:004"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>bubalehs</code>.
     */
    public final Bubalehs BUBALEHS = Bubalehs.BUBALEHS;

    /**
     * The table <code>departments</code>.
     */
    public final Departments DEPARTMENTS = Departments.DEPARTMENTS;

    /**
     * The table <code>employees</code>.
     */
    public final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>shakshoukas</code>.
     */
    public final Shakshoukas SHAKSHOUKAS = Shakshoukas.SHAKSHOUKAS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Bubalehs.BUBALEHS,
            Departments.DEPARTMENTS,
            Employees.EMPLOYEES,
            Shakshoukas.SHAKSHOUKAS
        );
    }
}
