/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.test.schema;


import com.razz.eva.test.schema.tables.Bubalehs;
import com.razz.eva.test.schema.tables.Employees;
import com.razz.eva.test.schema.tables.Shakshoukas;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:004"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BUBALEHS_EMPLOYEE_ID_NON_CONSUMED = Internal.createIndex(DSL.name("bubalehs_employee_id_non_consumed"), Bubalehs.BUBALEHS, new OrderField[] { Bubalehs.BUBALEHS.EMPLOYEE_ID }, true);
    public static final Index EMPLOYEES_EMAIL_IDX = Internal.createIndex(DSL.name("employees_email_idx"), Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.EMAIL }, true);
    public static final Index EMPLOYEES_NAME_IDX = Internal.createIndex(DSL.name("employees_name_idx"), Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.FIRST_NAME, Employees.EMPLOYEES.LAST_NAME }, true);
    public static final Index SHAKSHOUKAS_EMPLOYEE_ID_NON_CONSUMED = Internal.createIndex(DSL.name("shakshoukas_employee_id_non_consumed"), Shakshoukas.SHAKSHOUKAS, new OrderField[] { Shakshoukas.SHAKSHOUKAS.EMPLOYEE_ID }, true);
}
