/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.test.schema;


import com.razz.eva.test.schema.tables.Bubalehs;
import com.razz.eva.test.schema.tables.Departments;
import com.razz.eva.test.schema.tables.Employees;
import com.razz.eva.test.schema.tables.Shakshoukas;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:004"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bubalehs</code>.
     */
    public static final Bubalehs BUBALEHS = Bubalehs.BUBALEHS;

    /**
     * The table <code>departments</code>.
     */
    public static final Departments DEPARTMENTS = Departments.DEPARTMENTS;

    /**
     * The table <code>employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>shakshoukas</code>.
     */
    public static final Shakshoukas SHAKSHOUKAS = Shakshoukas.SHAKSHOUKAS;
}
