/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.events.db.tables.records;


import com.razz.eva.events.db.tables.UowEventsTemplate;
import java.time.Instant;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4",
        "schema version:001"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UowEventsTemplateRecord extends TableRecordImpl<UowEventsTemplateRecord> implements Record11<UUID, String, String, String, String, String, Instant, Instant, UUID[], String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>events.uow_events.id</code>.
     */
    public UowEventsTemplateRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>events.uow_events.name</code>.
     */
    public UowEventsTemplateRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>events.uow_events.idempotency_key</code>.
     */
    public UowEventsTemplateRecord setIdempotencyKey(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>events.uow_events.principal_name</code>.
     */
    public UowEventsTemplateRecord setPrincipalName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.principal_name</code>.
     */
    public String getPrincipalName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>events.uow_events.principal_id</code>.
     */
    public UowEventsTemplateRecord setPrincipalId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.principal_id</code>.
     */
    public String getPrincipalId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>events.uow_events.principal_context</code>.
     */
    public UowEventsTemplateRecord setPrincipalContext(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.principal_context</code>.
     */
    public String getPrincipalContext() {
        return (String) get(5);
    }

    /**
     * Setter for <code>events.uow_events.occurred_at</code>.
     */
    public UowEventsTemplateRecord setOccurredAt(Instant value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.occurred_at</code>.
     */
    public Instant getOccurredAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>events.uow_events.inserted_at</code>.
     */
    public UowEventsTemplateRecord setInsertedAt(Instant value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.inserted_at</code>.
     */
    public Instant getInsertedAt() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>events.uow_events.model_events</code>.
     */
    public UowEventsTemplateRecord setModelEvents(UUID[] value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.model_events</code>.
     */
    public UUID[] getModelEvents() {
        return (UUID[]) get(8);
    }

    /**
     * Setter for <code>events.uow_events.params</code>.
     */
    public UowEventsTemplateRecord setParams(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.params</code>.
     */
    public String getParams() {
        return (String) get(9);
    }

    /**
     * Setter for <code>events.uow_events.incremental_query_id</code>.
     */
    public UowEventsTemplateRecord setIncrementalQueryId(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.incremental_query_id</code>.
     */
    public Long getIncrementalQueryId() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<UUID, String, String, String, String, String, Instant, Instant, UUID[], String, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<UUID, String, String, String, String, String, Instant, Instant, UUID[], String, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.ID;
    }

    @Override
    public Field<String> field2() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.NAME;
    }

    @Override
    public Field<String> field3() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.IDEMPOTENCY_KEY;
    }

    @Override
    public Field<String> field4() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.PRINCIPAL_NAME;
    }

    @Override
    public Field<String> field5() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.PRINCIPAL_ID;
    }

    @Override
    public Field<String> field6() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.PRINCIPAL_CONTEXT;
    }

    @Override
    public Field<Instant> field7() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.OCCURRED_AT;
    }

    @Override
    public Field<Instant> field8() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.INSERTED_AT;
    }

    @Override
    public Field<UUID[]> field9() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.MODEL_EVENTS;
    }

    @Override
    public Field<String> field10() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.PARAMS;
    }

    @Override
    public Field<Long> field11() {
        return UowEventsTemplate.UOW_EVENTS_TEMPLATE.INCREMENTAL_QUERY_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getIdempotencyKey();
    }

    @Override
    public String component4() {
        return getPrincipalName();
    }

    @Override
    public String component5() {
        return getPrincipalId();
    }

    @Override
    public String component6() {
        return getPrincipalContext();
    }

    @Override
    public Instant component7() {
        return getOccurredAt();
    }

    @Override
    public Instant component8() {
        return getInsertedAt();
    }

    @Override
    public UUID[] component9() {
        return getModelEvents();
    }

    @Override
    public String component10() {
        return getParams();
    }

    @Override
    public Long component11() {
        return getIncrementalQueryId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getIdempotencyKey();
    }

    @Override
    public String value4() {
        return getPrincipalName();
    }

    @Override
    public String value5() {
        return getPrincipalId();
    }

    @Override
    public String value6() {
        return getPrincipalContext();
    }

    @Override
    public Instant value7() {
        return getOccurredAt();
    }

    @Override
    public Instant value8() {
        return getInsertedAt();
    }

    @Override
    public UUID[] value9() {
        return getModelEvents();
    }

    @Override
    public String value10() {
        return getParams();
    }

    @Override
    public Long value11() {
        return getIncrementalQueryId();
    }

    @Override
    public UowEventsTemplateRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value3(String value) {
        setIdempotencyKey(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value4(String value) {
        setPrincipalName(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value5(String value) {
        setPrincipalId(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value6(String value) {
        setPrincipalContext(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value7(Instant value) {
        setOccurredAt(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value8(Instant value) {
        setInsertedAt(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value9(UUID[] value) {
        setModelEvents(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value10(String value) {
        setParams(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord value11(Long value) {
        setIncrementalQueryId(value);
        return this;
    }

    @Override
    public UowEventsTemplateRecord values(UUID value1, String value2, String value3, String value4, String value5, String value6, Instant value7, Instant value8, UUID[] value9, String value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UowEventsTemplateRecord
     */
    public UowEventsTemplateRecord() {
        super(UowEventsTemplate.UOW_EVENTS_TEMPLATE);
    }

    /**
     * Create a detached, initialised UowEventsTemplateRecord
     */
    public UowEventsTemplateRecord(UUID id, String name, String idempotencyKey, String principalName, String principalId, String principalContext, Instant occurredAt, Instant insertedAt, UUID[] modelEvents, String params, Long incrementalQueryId) {
        super(UowEventsTemplate.UOW_EVENTS_TEMPLATE);

        setId(id);
        setName(name);
        setIdempotencyKey(idempotencyKey);
        setPrincipalName(principalName);
        setPrincipalId(principalId);
        setPrincipalContext(principalContext);
        setOccurredAt(occurredAt);
        setInsertedAt(insertedAt);
        setModelEvents(modelEvents);
        setParams(params);
        setIncrementalQueryId(incrementalQueryId);
    }
}
