/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.events.db.tables.records;


import com.razz.eva.events.db.tables.UowEvents;
import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.processing.Generated;
import java.time.Instant;
import java.util.UUID;


/**
 * PARTITIONED
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.4",
        "schema version:001"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UowEventsRecord extends TableRecordImpl<UowEventsRecord> implements Record10<UUID, String, String, String, String, Instant, Instant, UUID[], String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>events.uow_events.id</code>.
     */
    public UowEventsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>events.uow_events.name</code>.
     */
    public UowEventsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>events.uow_events.idempotency_key</code>.
     */
    public UowEventsRecord setIdempotencyKey(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>events.uow_events.principal_name</code>.
     */
    public UowEventsRecord setPrincipalName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.principal_name</code>.
     */
    public String getPrincipalName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>events.uow_events.principal_id</code>.
     */
    public UowEventsRecord setPrincipalId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.principal_id</code>.
     */
    public String getPrincipalId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>events.uow_events.occurred_at</code>.
     */
    public UowEventsRecord setOccurredAt(Instant value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.occurred_at</code>.
     */
    public Instant getOccurredAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>events.uow_events.inserted_at</code>.
     */
    public UowEventsRecord setInsertedAt(Instant value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.inserted_at</code>.
     */
    public Instant getInsertedAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>events.uow_events.model_events</code>.
     */
    public UowEventsRecord setModelEvents(UUID[] value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.model_events</code>.
     */
    public UUID[] getModelEvents() {
        return (UUID[]) get(7);
    }

    /**
     * Setter for <code>events.uow_events.params</code>.
     */
    public UowEventsRecord setParams(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.params</code>.
     */
    public String getParams() {
        return (String) get(8);
    }

    /**
     * Setter for <code>events.uow_events.incremental_query_id</code>.
     */
    public UowEventsRecord setIncrementalQueryId(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.incremental_query_id</code>.
     */
    public Long getIncrementalQueryId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, String, String, String, String, Instant, Instant, UUID[], String, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, String, String, String, String, Instant, Instant, UUID[], String, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UowEvents.UOW_EVENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return UowEvents.UOW_EVENTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return UowEvents.UOW_EVENTS.IDEMPOTENCY_KEY;
    }

    @Override
    public Field<String> field4() {
        return UowEvents.UOW_EVENTS.PRINCIPAL_NAME;
    }

    @Override
    public Field<String> field5() {
        return UowEvents.UOW_EVENTS.PRINCIPAL_ID;
    }

    @Override
    public Field<Instant> field6() {
        return UowEvents.UOW_EVENTS.OCCURRED_AT;
    }

    @Override
    public Field<Instant> field7() {
        return UowEvents.UOW_EVENTS.INSERTED_AT;
    }

    @Override
    public Field<UUID[]> field8() {
        return UowEvents.UOW_EVENTS.MODEL_EVENTS;
    }

    @Override
    public Field<String> field9() {
        return UowEvents.UOW_EVENTS.PARAMS;
    }

    @Override
    public Field<Long> field10() {
        return UowEvents.UOW_EVENTS.INCREMENTAL_QUERY_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getIdempotencyKey();
    }

    @Override
    public String component4() {
        return getPrincipalName();
    }

    @Override
    public String component5() {
        return getPrincipalId();
    }

    @Override
    public Instant component6() {
        return getOccurredAt();
    }

    @Override
    public Instant component7() {
        return getInsertedAt();
    }

    @Override
    public UUID[] component8() {
        return getModelEvents();
    }

    @Override
    public String component9() {
        return getParams();
    }

    @Override
    public Long component10() {
        return getIncrementalQueryId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getIdempotencyKey();
    }

    @Override
    public String value4() {
        return getPrincipalName();
    }

    @Override
    public String value5() {
        return getPrincipalId();
    }

    @Override
    public Instant value6() {
        return getOccurredAt();
    }

    @Override
    public Instant value7() {
        return getInsertedAt();
    }

    @Override
    public UUID[] value8() {
        return getModelEvents();
    }

    @Override
    public String value9() {
        return getParams();
    }

    @Override
    public Long value10() {
        return getIncrementalQueryId();
    }

    @Override
    public UowEventsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UowEventsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UowEventsRecord value3(String value) {
        setIdempotencyKey(value);
        return this;
    }

    @Override
    public UowEventsRecord value4(String value) {
        setPrincipalName(value);
        return this;
    }

    @Override
    public UowEventsRecord value5(String value) {
        setPrincipalId(value);
        return this;
    }

    @Override
    public UowEventsRecord value6(Instant value) {
        setOccurredAt(value);
        return this;
    }

    @Override
    public UowEventsRecord value7(Instant value) {
        setInsertedAt(value);
        return this;
    }

    @Override
    public UowEventsRecord value8(UUID[] value) {
        setModelEvents(value);
        return this;
    }

    @Override
    public UowEventsRecord value9(String value) {
        setParams(value);
        return this;
    }

    @Override
    public UowEventsRecord value10(Long value) {
        setIncrementalQueryId(value);
        return this;
    }

    @Override
    public UowEventsRecord values(UUID value1, String value2, String value3, String value4, String value5, Instant value6, Instant value7, UUID[] value8, String value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UowEventsRecord
     */
    public UowEventsRecord() {
        super(UowEvents.UOW_EVENTS);
    }

    /**
     * Create a detached, initialised UowEventsRecord
     */
    public UowEventsRecord(UUID id, String name, String idempotencyKey, String principalName, String principalId, Instant occurredAt, Instant insertedAt, UUID[] modelEvents, String params, Long incrementalQueryId) {
        super(UowEvents.UOW_EVENTS);

        setId(id);
        setName(name);
        setIdempotencyKey(idempotencyKey);
        setPrincipalName(principalName);
        setPrincipalId(principalId);
        setOccurredAt(occurredAt);
        setInsertedAt(insertedAt);
        setModelEvents(modelEvents);
        setParams(params);
        setIncrementalQueryId(incrementalQueryId);
    }
}
