/*
 * This file is generated by jOOQ.
 */
package com.razz.eva.events.db.tables.records;


import com.razz.eva.events.db.tables.UowEvents;

import java.time.Instant;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.5",
        "schema version:001"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UowEventsRecord extends TableRecordImpl<UowEventsRecord> implements Record8<UUID, String, String, String, String, Instant, UUID[], String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>events.uow_events.id</code>.
     */
    public UowEventsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>events.uow_events.name</code>.
     */
    public UowEventsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>events.uow_events.idempotency_key</code>.
     */
    public UowEventsRecord setIdempotencyKey(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>events.uow_events.principal_name</code>.
     */
    public UowEventsRecord setPrincipalName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.principal_name</code>.
     */
    public String getPrincipalName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>events.uow_events.principal_id</code>.
     */
    public UowEventsRecord setPrincipalId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.principal_id</code>.
     */
    public String getPrincipalId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>events.uow_events.occurred_at</code>.
     */
    public UowEventsRecord setOccurredAt(Instant value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.occurred_at</code>.
     */
    public Instant getOccurredAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>events.uow_events.model_events</code>.
     */
    public UowEventsRecord setModelEvents(UUID[] value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.model_events</code>.
     */
    public UUID[] getModelEvents() {
        return (UUID[]) get(6);
    }

    /**
     * Setter for <code>events.uow_events.params</code>.
     */
    public UowEventsRecord setParams(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>events.uow_events.params</code>.
     */
    public String getParams() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, String, String, String, Instant, UUID[], String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, String, String, String, Instant, UUID[], String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UowEvents.UOW_EVENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return UowEvents.UOW_EVENTS.NAME;
    }

    @Override
    public Field<String> field3() {
        return UowEvents.UOW_EVENTS.IDEMPOTENCY_KEY;
    }

    @Override
    public Field<String> field4() {
        return UowEvents.UOW_EVENTS.PRINCIPAL_NAME;
    }

    @Override
    public Field<String> field5() {
        return UowEvents.UOW_EVENTS.PRINCIPAL_ID;
    }

    @Override
    public Field<Instant> field6() {
        return UowEvents.UOW_EVENTS.OCCURRED_AT;
    }

    @Override
    public Field<UUID[]> field7() {
        return UowEvents.UOW_EVENTS.MODEL_EVENTS;
    }

    @Override
    public Field<String> field8() {
        return UowEvents.UOW_EVENTS.PARAMS;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getIdempotencyKey();
    }

    @Override
    public String component4() {
        return getPrincipalName();
    }

    @Override
    public String component5() {
        return getPrincipalId();
    }

    @Override
    public Instant component6() {
        return getOccurredAt();
    }

    @Override
    public UUID[] component7() {
        return getModelEvents();
    }

    @Override
    public String component8() {
        return getParams();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getIdempotencyKey();
    }

    @Override
    public String value4() {
        return getPrincipalName();
    }

    @Override
    public String value5() {
        return getPrincipalId();
    }

    @Override
    public Instant value6() {
        return getOccurredAt();
    }

    @Override
    public UUID[] value7() {
        return getModelEvents();
    }

    @Override
    public String value8() {
        return getParams();
    }

    @Override
    public UowEventsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UowEventsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UowEventsRecord value3(String value) {
        setIdempotencyKey(value);
        return this;
    }

    @Override
    public UowEventsRecord value4(String value) {
        setPrincipalName(value);
        return this;
    }

    @Override
    public UowEventsRecord value5(String value) {
        setPrincipalId(value);
        return this;
    }

    @Override
    public UowEventsRecord value6(Instant value) {
        setOccurredAt(value);
        return this;
    }

    @Override
    public UowEventsRecord value7(UUID[] value) {
        setModelEvents(value);
        return this;
    }

    @Override
    public UowEventsRecord value8(String value) {
        setParams(value);
        return this;
    }

    @Override
    public UowEventsRecord values(UUID value1, String value2, String value3, String value4, String value5, Instant value6, UUID[] value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UowEventsRecord
     */
    public UowEventsRecord() {
        super(UowEvents.UOW_EVENTS);
    }

    /**
     * Create a detached, initialised UowEventsRecord
     */
    public UowEventsRecord(UUID id, String name, String idempotencyKey, String principalName, String principalId, Instant occurredAt, UUID[] modelEvents, String params) {
        super(UowEvents.UOW_EVENTS);

        setId(id);
        setName(name);
        setIdempotencyKey(idempotencyKey);
        setPrincipalName(principalName);
        setPrincipalId(principalId);
        setOccurredAt(occurredAt);
        setModelEvents(modelEvents);
        setParams(params);
    }
}
